version: "3.7"

services:
    mongo:
        restart: always
        image: mongo:latest
        container_name: ${db_name}
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${admin_user}
            MONGO_INITDB_ROOT_PASSWORD: ${admin_pass}
            MONGO_INITDB_DATABASE: ${db_name}
            DB_USERNAME: ${db_user}
            DB_PASSWORD: ${db_pass}
            DB_PORT: ${db_port}
        volumes:
            - ./database:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        ports:
            - ${db_port}:27017
